### PR TITLE
Add support for RAMPS 1.4

### PR DESCRIPTION
**Pull request by jhitesma**
I had a spare RAMPS board and it seemed easier to just use that than wire up steppers manually.  It works quite well but is a bit overkill for something this simple!

### CODE REVIEW

**Comment by jhitesma** [comment]
oops, still learning how to do a PR...accidentally included other commits from @Yura80's PR.  I'll try again later.

**Comment by Yura80** [comment]
It's fine, you can include my commits in your PR

**Comment by Yura80** [comment]
Anyway, cocktailyogi doesn't seem to maintain this anymore

**Comment by jhitesma** [comment]
Yeah, didn't expect it to merge since he hasn't merged yours in over a year :(  

But wanted to do a clean PR just for the sake of doing it clean...but then I realized it really is built on top of yours anyway since @cocktailyogi didn't have any kind of board selection originally.  So, this is probably about as clean as I'll bother to get it anyway.  At least it's out there if it helps anyone!

**Pull request closed without merging**
